[package]
name = "nes_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit_field = "0.10.2"
once_cell = "1.17.1"

[dev-dependencies]
bitflags = "1.2.1"
